### ISSUE TITLE
depth_maps_2_calculate in function `_warp_coordinate_generate` and `_depth_warping`

### ISSUE THREAD

**Issue by YanhaoZhang** [lppllppl920/EndoscopyDepthEstimation-Pytorch#21]
Hi @lppllppl920 I notice that the variable depth_maps_2_calculate is a little bit different in those two functions. In `_warp_coordinate_generate`, the zeros in img_masks are set as 1.0e30 [here](https://github.com/lppllppl920/EndoscopyDepthEstimation-Pytorch/blob/6ec08d3e7c81ba65b1cb76affa00c53ee4868db0/models.py#L410-L411), while in `_depth_warping`, they are given a small value as epsilon [here](https://github.com/lppllppl920/EndoscopyDepthEstimation-Pytorch/blob/6ec08d3e7c81ba65b1cb76affa00c53ee4868db0/models.py#L509-L510). May I ask if you could explain a bit more on this? Many thanks.

**Comment by lppllppl920** [comment]
Hi Yanhao,

The main purpose of using either a small number or value here is to make sure the mask boundary is warped correctly. With the current PyTorch interpolation method, you can set both of these to epsilon because the interpolation allows you to assign a constant value to locations where the specified coordinates are out of boundary.

**Comment by YanhaoZhang** [comment]
Hi @lppllppl920 Thanks for your reply. Do you mean either a very large or a very small value will all work for warping the mask? Sorry I did not get what do you mean by "with the current PyTorch interpolation method". Do you mean for the latest PyTorch, I can use the very small value for warping the mask? Many thanks.

**Comment by lppllppl920** [comment]
The interpolation method provided by Pytorch has an argument named something like constant_value. That value will be used to fill in regions where coordinate values are out of the image region. With a very small value epsilon, coordinate values will be out of the image region and a zero value will be assigned to the corresponding location. The very large value will make the calculated coordinates to be close to (0, 0). This assumes the mask value at (0, 0) is out of the valid mask region. It is better to use the small value for both of these implementations now since pytorch has supported the constant value fill-in.

**Comment by YanhaoZhang** [comment]
@lppllppl920 Thanks a lot for your detailed explanation. I now understand it. :)
