### ISSUE TITLE
COLMAP settings and sharing of pretrained weights 

### ISSUE THREAD

**Issue by HashaamSaeed** [lppllppl920/EndoscopyDepthEstimation-Pytorch#32]
First of all congrats on the amazing papers that you have authored related to dense depth estimation and feature extraction , producing state of the art results .
 I am working on a similar project that you've worked on estimating depth from endoscopic videos and would like your help in regards to getting the trained weights for this implementation. I would be highly obliged for the help since I don't have the resources to generate SFM/MVS data and train it due to large compute times .

Also i have a few questions regarding COLMAP data generation 
1) Why do you use a pinhole model instead of a radial one considering the nature of endoscopic videos as seen in the text files of camera intrinsic parameters uploaded in example_training_data_root?

2) Colmap has automatic reconstruction and manual sparse/dense reconstruction where you produce dense reconstruction doing everything step by step can you share the parameters you used exactly to produce the training data .

Thanks

**Comment by lppllppl920** [comment]
Hi,

I used pinhole camera model for simplicity because my images have been undistorted. You can use any other models as long as the camera projection is changed correspondingly.

I did not use COLMAP to generate training data in this work. But the general direction of using COLMAP to generate data is to use DSP-SIFT and try to tune the parameters to increase candidate keypoints per frame.

**Comment by HashaamSaeed** [comment]
Thank you for the answers. Sorry, I opened an issue related to COLMAP on this repo, but since the SFM technique you're using isn't publicly available I asked it here.

Also if possible, can you share the trained weights?
